-- AUTO-GENERATED by scripts/extract-item-catalog.mjs — do not edit by hand
-- Source: dump/catalog/instances.jsonl (Items/gears + GridItemFolder equipmentType)

local M = {}

M.SLOT_ORDER = { "helmet", "face_cover", "armor", "lower_armor", "gloves", "backpack" }

M.by_name = {
    ["5.11 Hexgrid Plate Carrier"] = "armor",
    ["A7 Delta Riot Helmet"] = "helmet",
    ["Altyn bulletproof Helmet"] = "helmet",
    ["DC 800 High Cut Combat Helmet"] = "helmet",
    ["FAST MT Helmet"] = "helmet",
    ["FORT-9 Heavy Assault Rig"] = "armor",
    ["FORTIS MK.II Gloves"] = "gloves",
    ["Forest Green Ghillie Suit"] = "armor",
    ["Gorynych-S \"Sten\" Assault Rig"] = "armor",
    ["Gorynych-S _Sten_ Assault Rig"] = "armor",
    ["Gzhel-K Body Armor"] = "armor",
    ["HVC Gen4 Body Armor"] = "armor",
    ["HVC Gen4 Body Armor (HMK)"] = "armor",
    ["HVC Plate Carrier"] = "armor",
    ["Hand Wraps"] = "gloves",
    ["Integrated Tactical Plate Carrier"] = "armor",
    ["Korund-VM Body Armor"] = "armor",
    ["M40-1 Gas Mask"] = "face_cover",
    ["M40-2 Gas Mask"] = "face_cover",
    ["MBC Plate Carrier"] = "armor",
    ["MOTR Concealable Reinforced Vest"] = "armor",
    ["MSA Paraclete Plate Carrier"] = "armor",
    ["Mask"] = "face_cover",
    ["Maska-1SCh \"Voin\" Helmet"] = "helmet",
    ["Maska-1SCh Helmet"] = "helmet",
    ["Maska-1SCh _Voin_ Helmet"] = "helmet",
    ["Military Backpack"] = "backpack",
    ["Military Helmet"] = "helmet",
    ["PICO-A1 Light Lower Body Armor"] = "lower_armor",
    ["PICO-A2 Heavy Lower Body Armor"] = "lower_armor",
    ["PX27 Headlamp"] = "helmet",
    ["Precisive Grips"] = "gloves",
    ["ROVER Motorcycle Helmet"] = "helmet",
    ["S&M Backpack"] = "backpack",
    ["Scuba Gear"] = "face_cover",
    ["Slick Plate Carrier"] = "armor",
    ["Sling Bag"] = "backpack",
    ["T178 Raid Backpack"] = "backpack",
    ["Tagilla's welding mask \"Gorilla\""] = "face_cover",
    ["Tagilla's welding mask \"UBEY\""] = "face_cover",
    ["ULACH IIIA Helmet"] = "helmet",
    ["Xtreme Motorcycle Helmet"] = "helmet",
}

function M.get_slot(name)
    if not name or name == "" then return nil end
    return M.by_name[name]
end

function M.is_gear(name)
    return M.get_slot(name) ~= nil
end

return M
