local M = {}

M.SECTIONS = {
    {
        ["id"] = "ammo",
        ["label"] = "Ammo",
        ["items"] = {
            ".338 Lapua Magnum",
            ".408 Cheyenne Tactical",
            ".45 ACP",
            ".50 Action Express",
            "12 Gauge Buckshot",
            "23x75mm Shrapnel-10",
            "23x75mm Zvezda flashbang round",
            "4.6x30mm",
            "40x46mm M406 grenade",
            "5.45x39mm",
            "5.56x45mm NATO",
            "5.7x28mm",
            "5.8x42mm",
            "7.62x39mm",
            "7.62x51mm NATO",
            "7.62x54mmR",
            "9x18mm",
            "9x19mm",
            "9x39mm",
            "PG-7V HEAT grenade",
        },
    },
    {
        ["id"] = "attachments",
        ["label"] = "Attachments",
        ["items"] = {
            "ACOG TA11D 3.5x35 riflescope",
            "AN PEQ-15 tactical device",
            "Angled foregrip",
            "Bramit 7.62x54R sound suppressor",
            "CMT ZCOMP linear compensator",
            "Colt 4x20 riflescope",
            "EOTech 553 holographic sight",
            "Gemtech SFN-57 5.7x28 sound suppressor",
            "HK MP7 SD 2 4.6x30 sound suppressor",
            "HVC-10T Night Vision Goggles",
            "Improvised plastic sound suppressor",
            "Kahles K624i 6-24x riflescope",
            "LVPO 10x28 riflescope",
            "Leupold Mark 8 8x24 riflescope",
            "MAC-10 sound suppressor",
            "MP9 9x19 sound suppressor",
            "NCStar AQPTLMG Compact Green Laser",
            "Nightforce ATACR 7-35x56",
            "NovaTec RMR reflex sight",
            "NovaTec reflex sight",
            "ODWave 556 5.56x45 sound suppressor",
            "OKP-7 reflex sight",
            "Oil Filter sound suppressor",
            "PBS-1 sound suppressor",
            "PSO-1 4x24 scope",
            "PU-1 3.5x riflescope",
            "PureFire X300 Ultra",
            "QDSS-NT4 5.56x45 sound suppressor",
            "RK-1 tactical foregrip",
            "SHARK muzzle brake",
            "SV-98 7.62x54R sound suppressor",
            "SilKo Osprey 9 9x19 sound suppressor",
            "SilKo Salvo 12 12ga sound suppressor",
            "SureFire 3-prong flash hider",
            "SureFire 4-prong flash hider",
            "T-7 Thermal Goggles",
            "Type 04-1 holographic sight",
            "UH-1 holographic sight",
            "VSS modern stock",
            "Vanish 30 5.56x45 sound suppressor",
            "Vertical foregrip",
            "YMA95-1 3.5x riflescope",
        },
    },
    {
        ["id"] = "buildings",
        ["label"] = "Buildings",
        ["items"] = {
            "Aluminium Nails",
            "Capacitors",
            "Chemical Solution",
            "Compact antenna",
            "Corrugated Tube",
            "Duct tape",
            "Gears",
            "Glue",
            "Magnet",
            "Metal fuel tank",
            "Mounting Foam",
            "Nails",
            "Pipecleaner",
            "Scrap Metal",
            "Sealing Foam",
            "Sodium Bicarbonate",
            "Titanium Alloy Plate",
            "Tube of cold welding",
        },
    },
    {
        ["id"] = "containers",
        ["label"] = "Containers",
        ["items"] = {
            "Ammunition case",
            "Blackberryz Wallet",
            "Keycard holder case",
            "Weapon case",
        },
    },
    {
        ["id"] = "documents",
        ["label"] = "Documents",
        ["items"] = {
            "Alien on a Rampage Book",
            "Bad Guys",
            "CJJ’s Guide to Making Money",
            "Dawnscript Fragment",
            "Diary",
            "Intelligence folder",
            "Nomad Route Notes",
            "Printer Paper",
            "Sealed black file",
            "Shards in the Code  Season One",
        },
    },
    {
        ["id"] = "electronics",
        ["label"] = "Electronics",
        ["items"] = {
            "AA Battery",
            "Cables",
            "Car Battery",
            "Geolocator",
            "Golden Smartphone",
            "Graphics card",
            "Microcircuits",
            "Power unit",
            "Powerbank",
            "RAM",
            "SAS drive",
            "SSD",
            "Smartphone",
            "Tank Battery",
            "USB extension cable",
        },
    },
    {
        ["id"] = "gears",
        ["label"] = "Gears",
        ["items"] = {
            "5.11 Hexgrid Plate Carrier",
            "A7 Delta Riot Helmet",
            "Altyn bulletproof Helmet",
            "DC 800 High Cut Combat Helmet",
            "FAST MT Helmet",
            "FORT-9 Heavy Assault Rig",
            "FORTIS MK.II Gloves",
            "Forest Green Ghillie Suit",
            "Gorynych-S  Sten  Assault Rig",
            "Gzhel-K Body Armor",
            "HVC Gen4 Body Armor",
            "HVC Gen4 Body Armor (HMK)",
            "HVC Plate Carrier",
            "Hand Wraps",
            "Integrated Tactical Plate Carrier",
            "Korund-VM Body Armor",
            "M40-1 Gas Mask",
            "M40-2 Gas Mask",
            "MBC Plate Carrier",
            "MOTR Concealable Reinforced Vest",
            "MSA Paraclete Plate Carrier",
            "Mask",
            "Maska-1SCh  Voin  Helmet",
            "Maska-1SCh Helmet",
            "Military Backpack",
            "Military Helmet",
            "PICO-A1 Light Lower Body Armor",
            "PICO-A2 Heavy Lower Body Armor",
            "PX27 Headlamp",
            "Precisive Grips",
            "ROVER Motorcycle Helmet",
            "S&M Backpack",
            "Scuba Gear",
            "Slick Plate Carrier",
            "Sling Bag",
            "T178 Raid Backpack",
            "Tagilla's welding mask  Gorilla ",
            "Tagilla's welding mask  UBEY ",
            "ULACH IIIA Helmet",
            "Xtreme Motorcycle Helmet",
        },
    },
    {
        ["id"] = "households",
        ["label"] = "Households",
        ["items"] = {
            "Antique teapot",
            "Box of Sugar",
            "Can of Beef",
            "Can of Mackerel",
            "Can of Salt",
            "Can of Tuna",
            "Construction Measuring Tape",
            "Deodorant",
            "Empty dish",
            "Flash Drive",
            "Flour",
            "Havocola Cherry Burn",
            "Havocola Classic",
            "Homemade Soap",
            "Insecticide spray",
            "Insects Spray",
            "Ketchup",
            "Mayonnaise",
            "Meat grinder",
            "Mug",
            "Northmont Sparkling Cider",
            "Orange juice carton",
            "Pack of matches",
            "Palmolive handwash",
            "Perfume",
            "Porcelain",
            "Rat Poison",
            "Scissors",
            "Sewing Kit",
            "Shampoo",
            "Spoon",
            "Sticky Tape",
            "String",
            "Toilet paper",
            "Toothpaste",
            "Vegetable oil",
            "Watch",
        },
    },
    {
        ["id"] = "mags",
        ["label"] = "Mags",
        ["items"] = {
            "5.56x45 Beta C-Mag 100-round drum magazine",
            "5.56x45 Colt AR-15 STANAG 20-round magazine",
            "5.56x45 Colt AR-15 STANAG 30-round magazine",
            "5.56x45 Colt AR-15 STANAG 60-round magazine",
            "5.56x45 PMAG 60-round magazine",
            "5.56x45 TV 100-round magazine",
            "9x39 20-round magazine",
            "9x39 30-round magazine",
            "AK 7.62x39 40-round magazine",
            "AK 7.62x39 Magpul PMAG 30 GEN M3 30-round magazine",
            "AK-74 5.45x39 6L20 30-round magazine",
            "AK-74 5.45x39 Magpul PMAG 30 GEN M3 30-round magazine",
            "AWP .338 Lapua Magnum 5-round magazine",
            "Beretta 92X 9x19 17-round magazine",
            "DP-27 7.62x54mmR 47-round pan magazine",
            "Deagle .50 AE 7-round magazine",
            "FN P90 5.7x28 50-round magazine",
            "FN SCAR-H 7.62x51 20-round magazine",
            "FN SCAR-H 7.62x51 50-round drum magazine",
            "GL 9x19 17-round magazine",
            "GL 9x19 33-round magazine",
            "GL 9x19 50-round drum magazine",
            "HK MP5 9x19 30-round magazine",
            "HK MP5 9x19 50-round drum magazine",
            "HK MP7 4.6x30 40-round magazine",
            "HK UMP .45 ACP 25-round magazine",
            "M1911A1 .45 ACP 7-round magazine",
            "M200 .408 Cheyenne Tactical 5-round magazine",
            "MAC-10 9x19 30-round magazine",
            "MP34 9x19 32-round magazine",
            "MP9 9x19 30-round magazine",
            "Makarov 9x18 8-round magazine",
            "Mk14 7.62x51 10-round magazine",
            "RPK-16 5.45x39 95-round drum magazine",
            "SA58 FAL 7.62x51 20-round magazine",
            "SA58 FAL 7.62x51 50-round drum magazine",
            "SV-98 7.62x51 10-round magazine",
            "SVD 7.62x54mmR 10-round magazine",
            "Type 95 5.8x42mm 30-round magazine",
        },
    },
    {
        ["id"] = "medical",
        ["label"] = "Medical",
        ["items"] = {
            "Defibrillator monitor",
            "Insulin pump",
            "Medical bloodset",
            "Medical set",
            "Pile of meds",
            "Rapid Emergency AED Compact Tool",
            "Sodium Chloride",
            "Surgical kit",
            "Vitamins",
            "White tube",
        },
    },
    {
        ["id"] = "tools",
        ["label"] = "Tools",
        ["items"] = {
            "Awl",
            "Bimetallic Thermometer",
            "Electric Drill",
            "Field repair kit",
            "Gunpowder",
            "Long Screwdriver",
            "Measuring tape",
            "Metal Awl",
            "Metal Cutting Scissors",
            "Pipe wrench",
            "Screwdriver",
            "Weapon parts",
            "Wrench",
            "XLaser pointer module",
        },
    },
    {
        ["id"] = "valuables",
        ["label"] = "Valuables",
        ["items"] = {
            "0.2 BTC",
            "AK-1 Helm",
            "Blahaj Baja Blast Pen",
            "Conductor's Gold Pocket Watch",
            "Cottage Cache Key",
            "Deluxe Pirate Hook",
            "Diamond ring",
            "Domino Crown",
            "FORTIS Coastal Outpost Cache Key",
            "FORTIS Level-0 keycard",
            "FORTIS Level-1 keycard",
            "FORTIS Level-2 keycard",
            "FORTIS Level-3 keycard",
            "FORTIS Level-4 keycard",
            "FORTIS Level-5 keycard",
            "FORTIS Level-6 keycard",
            "Glim Charm",
            "Gold Trophy",
            "Gold bar",
            "Golden Cube",
            "Golden Skull",
            "Golden Watch",
            "Jiffy Domino Top Hat",
            "Magic Lamp",
            "North Dolphin Hospital Safe Key",
            "Spork 777",
            "Sport Complex “Lych Zdorovya” Cache Key",
            "The 5th Annual Bloxy Award",
            "The Cap Of The Rebelled",
            "The Greatest Admin plushie",
            "Thraggorian Arms 3516",
            "Vintage Gold Crown",
            "XDM's Red Helm",
            "iDog Bot",
        },
    },
}

M.NAME_TO_CATEGORY = {
    [".338 Lapua Magnum"] = "ammo",
    [".408 Cheyenne Tactical"] = "ammo",
    [".45 ACP"] = "ammo",
    [".50 Action Express"] = "ammo",
    ["12 Gauge Buckshot"] = "ammo",
    ["23x75mm Shrapnel-10"] = "ammo",
    ["23x75mm Zvezda flashbang round"] = "ammo",
    ["4.6x30mm"] = "ammo",
    ["40x46mm M406 grenade"] = "ammo",
    ["5.45x39mm"] = "ammo",
    ["5.56x45mm NATO"] = "ammo",
    ["5.7x28mm"] = "ammo",
    ["5.8x42mm"] = "ammo",
    ["7.62x39mm"] = "ammo",
    ["7.62x51mm NATO"] = "ammo",
    ["7.62x54mmR"] = "ammo",
    ["9x18mm"] = "ammo",
    ["9x19mm"] = "ammo",
    ["9x39mm"] = "ammo",
    ["PG-7V HEAT grenade"] = "ammo",
    ["ACOG TA11D 3.5x35 riflescope"] = "attachments",
    ["AN PEQ-15 tactical device"] = "attachments",
    ["Angled foregrip"] = "attachments",
    ["Bramit 7.62x54R sound suppressor"] = "attachments",
    ["CMT ZCOMP linear compensator"] = "attachments",
    ["Colt 4x20 riflescope"] = "attachments",
    ["EOTech 553 holographic sight"] = "attachments",
    ["Gemtech SFN-57 5.7x28 sound suppressor"] = "attachments",
    ["HK MP7 SD 2 4.6x30 sound suppressor"] = "attachments",
    ["HVC-10T Night Vision Goggles"] = "attachments",
    ["Improvised plastic sound suppressor"] = "attachments",
    ["Kahles K624i 6-24x riflescope"] = "attachments",
    ["LVPO 10x28 riflescope"] = "attachments",
    ["Leupold Mark 8 8x24 riflescope"] = "attachments",
    ["MAC-10 sound suppressor"] = "attachments",
    ["MP9 9x19 sound suppressor"] = "attachments",
    ["NCStar AQPTLMG Compact Green Laser"] = "attachments",
    ["Nightforce ATACR 7-35x56"] = "attachments",
    ["NovaTec RMR reflex sight"] = "attachments",
    ["NovaTec reflex sight"] = "attachments",
    ["ODWave 556 5.56x45 sound suppressor"] = "attachments",
    ["OKP-7 reflex sight"] = "attachments",
    ["Oil Filter sound suppressor"] = "attachments",
    ["PBS-1 sound suppressor"] = "attachments",
    ["PSO-1 4x24 scope"] = "attachments",
    ["PU-1 3.5x riflescope"] = "attachments",
    ["PureFire X300 Ultra"] = "attachments",
    ["QDSS-NT4 5.56x45 sound suppressor"] = "attachments",
    ["RK-1 tactical foregrip"] = "attachments",
    ["SHARK muzzle brake"] = "attachments",
    ["SV-98 7.62x54R sound suppressor"] = "attachments",
    ["SilKo Osprey 9 9x19 sound suppressor"] = "attachments",
    ["SilKo Salvo 12 12ga sound suppressor"] = "attachments",
    ["SureFire 3-prong flash hider"] = "attachments",
    ["SureFire 4-prong flash hider"] = "attachments",
    ["T-7 Thermal Goggles"] = "attachments",
    ["Type 04-1 holographic sight"] = "attachments",
    ["UH-1 holographic sight"] = "attachments",
    ["VSS modern stock"] = "attachments",
    ["Vanish 30 5.56x45 sound suppressor"] = "attachments",
    ["Vertical foregrip"] = "attachments",
    ["YMA95-1 3.5x riflescope"] = "attachments",
    ["Aluminium Nails"] = "buildings",
    ["Capacitors"] = "buildings",
    ["Chemical Solution"] = "buildings",
    ["Compact antenna"] = "buildings",
    ["Corrugated Tube"] = "buildings",
    ["Duct tape"] = "buildings",
    ["Gears"] = "buildings",
    ["Glue"] = "buildings",
    ["Magnet"] = "buildings",
    ["Metal fuel tank"] = "buildings",
    ["Mounting Foam"] = "buildings",
    ["Nails"] = "buildings",
    ["Pipecleaner"] = "buildings",
    ["Scrap Metal"] = "buildings",
    ["Sealing Foam"] = "buildings",
    ["Sodium Bicarbonate"] = "buildings",
    ["Titanium Alloy Plate"] = "buildings",
    ["Tube of cold welding"] = "buildings",
    ["Ammunition case"] = "containers",
    ["Blackberryz Wallet"] = "containers",
    ["Keycard holder case"] = "containers",
    ["Weapon case"] = "containers",
    ["Alien on a Rampage Book"] = "documents",
    ["Bad Guys"] = "documents",
    ["CJJ’s Guide to Making Money"] = "documents",
    ["Dawnscript Fragment"] = "documents",
    ["Diary"] = "documents",
    ["Intelligence folder"] = "documents",
    ["Nomad Route Notes"] = "documents",
    ["Printer Paper"] = "documents",
    ["Sealed black file"] = "documents",
    ["Shards in the Code  Season One"] = "documents",
    ["AA Battery"] = "electronics",
    ["Cables"] = "electronics",
    ["Car Battery"] = "electronics",
    ["Geolocator"] = "electronics",
    ["Golden Smartphone"] = "electronics",
    ["Graphics card"] = "electronics",
    ["Microcircuits"] = "electronics",
    ["Power unit"] = "electronics",
    ["Powerbank"] = "electronics",
    ["RAM"] = "electronics",
    ["SAS drive"] = "electronics",
    ["SSD"] = "electronics",
    ["Smartphone"] = "electronics",
    ["Tank Battery"] = "electronics",
    ["USB extension cable"] = "electronics",
    ["5.11 Hexgrid Plate Carrier"] = "gears",
    ["A7 Delta Riot Helmet"] = "gears",
    ["Altyn bulletproof Helmet"] = "gears",
    ["DC 800 High Cut Combat Helmet"] = "gears",
    ["FAST MT Helmet"] = "gears",
    ["FORT-9 Heavy Assault Rig"] = "gears",
    ["FORTIS MK.II Gloves"] = "gears",
    ["Forest Green Ghillie Suit"] = "gears",
    ["Gorynych-S  Sten  Assault Rig"] = "gears",
    ["Gzhel-K Body Armor"] = "gears",
    ["HVC Gen4 Body Armor"] = "gears",
    ["HVC Gen4 Body Armor (HMK)"] = "gears",
    ["HVC Plate Carrier"] = "gears",
    ["Hand Wraps"] = "gears",
    ["Integrated Tactical Plate Carrier"] = "gears",
    ["Korund-VM Body Armor"] = "gears",
    ["M40-1 Gas Mask"] = "gears",
    ["M40-2 Gas Mask"] = "gears",
    ["MBC Plate Carrier"] = "gears",
    ["MOTR Concealable Reinforced Vest"] = "gears",
    ["MSA Paraclete Plate Carrier"] = "gears",
    ["Mask"] = "gears",
    ["Maska-1SCh  Voin  Helmet"] = "gears",
    ["Maska-1SCh Helmet"] = "gears",
    ["Military Backpack"] = "gears",
    ["Military Helmet"] = "gears",
    ["PICO-A1 Light Lower Body Armor"] = "gears",
    ["PICO-A2 Heavy Lower Body Armor"] = "gears",
    ["PX27 Headlamp"] = "gears",
    ["Precisive Grips"] = "gears",
    ["ROVER Motorcycle Helmet"] = "gears",
    ["S&M Backpack"] = "gears",
    ["Scuba Gear"] = "gears",
    ["Slick Plate Carrier"] = "gears",
    ["Sling Bag"] = "gears",
    ["T178 Raid Backpack"] = "gears",
    ["Tagilla's welding mask  Gorilla "] = "gears",
    ["Tagilla's welding mask  UBEY "] = "gears",
    ["ULACH IIIA Helmet"] = "gears",
    ["Xtreme Motorcycle Helmet"] = "gears",
    ["Antique teapot"] = "households",
    ["Box of Sugar"] = "households",
    ["Can of Beef"] = "households",
    ["Can of Mackerel"] = "households",
    ["Can of Salt"] = "households",
    ["Can of Tuna"] = "households",
    ["Construction Measuring Tape"] = "households",
    ["Deodorant"] = "households",
    ["Empty dish"] = "households",
    ["Flash Drive"] = "households",
    ["Flour"] = "households",
    ["Havocola Cherry Burn"] = "households",
    ["Havocola Classic"] = "households",
    ["Homemade Soap"] = "households",
    ["Insecticide spray"] = "households",
    ["Insects Spray"] = "households",
    ["Ketchup"] = "households",
    ["Mayonnaise"] = "households",
    ["Meat grinder"] = "households",
    ["Mug"] = "households",
    ["Northmont Sparkling Cider"] = "households",
    ["Orange juice carton"] = "households",
    ["Pack of matches"] = "households",
    ["Palmolive handwash"] = "households",
    ["Perfume"] = "households",
    ["Porcelain"] = "households",
    ["Rat Poison"] = "households",
    ["Scissors"] = "households",
    ["Sewing Kit"] = "households",
    ["Shampoo"] = "households",
    ["Spoon"] = "households",
    ["Sticky Tape"] = "households",
    ["String"] = "households",
    ["Toilet paper"] = "households",
    ["Toothpaste"] = "households",
    ["Vegetable oil"] = "households",
    ["Watch"] = "households",
    ["5.56x45 Beta C-Mag 100-round drum magazine"] = "mags",
    ["5.56x45 Colt AR-15 STANAG 20-round magazine"] = "mags",
    ["5.56x45 Colt AR-15 STANAG 30-round magazine"] = "mags",
    ["5.56x45 Colt AR-15 STANAG 60-round magazine"] = "mags",
    ["5.56x45 PMAG 60-round magazine"] = "mags",
    ["5.56x45 TV 100-round magazine"] = "mags",
    ["9x39 20-round magazine"] = "mags",
    ["9x39 30-round magazine"] = "mags",
    ["AK 7.62x39 40-round magazine"] = "mags",
    ["AK 7.62x39 Magpul PMAG 30 GEN M3 30-round magazine"] = "mags",
    ["AK-74 5.45x39 6L20 30-round magazine"] = "mags",
    ["AK-74 5.45x39 Magpul PMAG 30 GEN M3 30-round magazine"] = "mags",
    ["AWP .338 Lapua Magnum 5-round magazine"] = "mags",
    ["Beretta 92X 9x19 17-round magazine"] = "mags",
    ["DP-27 7.62x54mmR 47-round pan magazine"] = "mags",
    ["Deagle .50 AE 7-round magazine"] = "mags",
    ["FN P90 5.7x28 50-round magazine"] = "mags",
    ["FN SCAR-H 7.62x51 20-round magazine"] = "mags",
    ["FN SCAR-H 7.62x51 50-round drum magazine"] = "mags",
    ["GL 9x19 17-round magazine"] = "mags",
    ["GL 9x19 33-round magazine"] = "mags",
    ["GL 9x19 50-round drum magazine"] = "mags",
    ["HK MP5 9x19 30-round magazine"] = "mags",
    ["HK MP5 9x19 50-round drum magazine"] = "mags",
    ["HK MP7 4.6x30 40-round magazine"] = "mags",
    ["HK UMP .45 ACP 25-round magazine"] = "mags",
    ["M1911A1 .45 ACP 7-round magazine"] = "mags",
    ["M200 .408 Cheyenne Tactical 5-round magazine"] = "mags",
    ["MAC-10 9x19 30-round magazine"] = "mags",
    ["MP34 9x19 32-round magazine"] = "mags",
    ["MP9 9x19 30-round magazine"] = "mags",
    ["Makarov 9x18 8-round magazine"] = "mags",
    ["Mk14 7.62x51 10-round magazine"] = "mags",
    ["RPK-16 5.45x39 95-round drum magazine"] = "mags",
    ["SA58 FAL 7.62x51 20-round magazine"] = "mags",
    ["SA58 FAL 7.62x51 50-round drum magazine"] = "mags",
    ["SV-98 7.62x51 10-round magazine"] = "mags",
    ["SVD 7.62x54mmR 10-round magazine"] = "mags",
    ["Type 95 5.8x42mm 30-round magazine"] = "mags",
    ["Defibrillator monitor"] = "medical",
    ["Insulin pump"] = "medical",
    ["Medical bloodset"] = "medical",
    ["Medical set"] = "medical",
    ["Pile of meds"] = "medical",
    ["Rapid Emergency AED Compact Tool"] = "medical",
    ["Sodium Chloride"] = "medical",
    ["Surgical kit"] = "medical",
    ["Vitamins"] = "medical",
    ["White tube"] = "medical",
    ["Awl"] = "tools",
    ["Bimetallic Thermometer"] = "tools",
    ["Electric Drill"] = "tools",
    ["Field repair kit"] = "tools",
    ["Gunpowder"] = "tools",
    ["Long Screwdriver"] = "tools",
    ["Measuring tape"] = "tools",
    ["Metal Awl"] = "tools",
    ["Metal Cutting Scissors"] = "tools",
    ["Pipe wrench"] = "tools",
    ["Screwdriver"] = "tools",
    ["Weapon parts"] = "tools",
    ["Wrench"] = "tools",
    ["XLaser pointer module"] = "tools",
    ["0.2 BTC"] = "valuables",
    ["AK-1 Helm"] = "valuables",
    ["Blahaj Baja Blast Pen"] = "valuables",
    ["Conductor's Gold Pocket Watch"] = "valuables",
    ["Cottage Cache Key"] = "valuables",
    ["Deluxe Pirate Hook"] = "valuables",
    ["Diamond ring"] = "valuables",
    ["Domino Crown"] = "valuables",
    ["FORTIS Coastal Outpost Cache Key"] = "valuables",
    ["FORTIS Level-0 keycard"] = "valuables",
    ["FORTIS Level-1 keycard"] = "valuables",
    ["FORTIS Level-2 keycard"] = "valuables",
    ["FORTIS Level-3 keycard"] = "valuables",
    ["FORTIS Level-4 keycard"] = "valuables",
    ["FORTIS Level-5 keycard"] = "valuables",
    ["FORTIS Level-6 keycard"] = "valuables",
    ["Glim Charm"] = "valuables",
    ["Gold Trophy"] = "valuables",
    ["Gold bar"] = "valuables",
    ["Golden Cube"] = "valuables",
    ["Golden Skull"] = "valuables",
    ["Golden Watch"] = "valuables",
    ["Jiffy Domino Top Hat"] = "valuables",
    ["Magic Lamp"] = "valuables",
    ["North Dolphin Hospital Safe Key"] = "valuables",
    ["Spork 777"] = "valuables",
    ["Sport Complex “Lych Zdorovya” Cache Key"] = "valuables",
    ["The 5th Annual Bloxy Award"] = "valuables",
    ["The Cap Of The Rebelled"] = "valuables",
    ["The Greatest Admin plushie"] = "valuables",
    ["Thraggorian Arms 3516"] = "valuables",
    ["Vintage Gold Crown"] = "valuables",
    ["XDM's Red Helm"] = "valuables",
    ["iDog Bot"] = "valuables",
}

function M.resolve(name)
    if not name or name == "" then return nil end
    return M.NAME_TO_CATEGORY[name]
end

function M.section(id)
    for i = 1, #M.SECTIONS do
        local s = M.SECTIONS[i]
        if s.id == id then
            return s, i
        end
    end
    return nil
end

function M.section_index(id)
    for i = 1, #M.SECTIONS do
        if M.SECTIONS[i].id == id then
            return i
        end
    end
    return nil
end

return M
